"""Practical visual evidence for Lecture 7.

The augmentation and MixUp/CutMix figures apply deterministic pixel operations
to fixed, high-resolution course-generated source photographs.  Keeping the
operations code-driven makes the comparison inspectable while avoiding the
projection-scale pixelation of the former 32x32 CIFAR-10 examples.  The measured
regularization experiment remains CIFAR-10 and is generated by the separate
``cifar_regularization_experiment.py`` script.

The MC-dropout figure is explicitly a schematic bridge, not an empirical
calibration claim.

Run from the ``dl-teaching`` repository root:

    uv run --with matplotlib --with pillow --with numpy \
      --with 'torch>=2.2' --with 'torchvision>=0.17' \
      python lecture7/diagrams/l7_practical_figs.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import torch
from PIL import Image, ImageEnhance, ImageOps
from torchvision.transforms import v2


INK = "#23373B"
ACC = "#EB811B"
TEAL = "#2C7A7B"
GREEN = "#14B03D"
MUTED = "#6E7F82"
RED = "#D64550"
BLUE = "#2B6CB0"
CREAM = "#F7F5F0"

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "lecture7" / "figures"
OUT.mkdir(parents=True, exist_ok=True)
SOURCE_DIR = OUT / "sources"
AUGMENTATION_CAT = SOURCE_DIR / "augmentation_cat_imagen_v2.png"
MIXUP_PAIR = SOURCE_DIR / "mixup_cat_dog_imagen.png"

mpl.rcParams.update(
    {
        "figure.facecolor": "none",
        "axes.facecolor": "none",
        "savefig.facecolor": "none",
        "savefig.transparent": True,
        "font.family": "sans-serif",
        "font.sans-serif": ["IBM Plex Sans", "DejaVu Sans", "Arial"],
        "text.color": INK,
        "axes.edgecolor": INK,
        "axes.labelcolor": INK,
        "xtick.color": INK,
        "ytick.color": INK,
        "axes.linewidth": 1.0,
        "font.size": 13,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.solid_capstyle": "round",
    }
)


def save(
    fig: plt.Figure,
    name: str,
    *,
    raster_only: bool = False,
    dpi: int = 220,
) -> None:
    fig.savefig(OUT / f"{name}.png", bbox_inches="tight", dpi=dpi, transparent=True)
    if not raster_only:
        fig.savefig(OUT / f"{name}.svg", bbox_inches="tight", transparent=True)
    plt.close(fig)


def load_rgb(path: Path) -> Image.Image:
    if not path.exists():
        raise FileNotFoundError(f"Missing source photograph: {path}")
    with Image.open(path) as image:
        return image.convert("RGB")


def square_crop(
    image: Image.Image,
    *,
    vertical_bias: float = 0.5,
    horizontal_bias: float = 0.5,
) -> Image.Image:
    """Crop a square with independent horizontal and vertical bias."""
    width, height = image.size
    side = min(width, height)
    available_x = width - side
    left = int(round(available_x * horizontal_bias))
    left = min(max(left, 0), available_x)
    available_y = height - side
    top = int(round(available_y * vertical_bias))
    top = min(max(top, 0), available_y)
    return image.crop((left, top, left + side, top + side))


def load_teaching_photos() -> tuple[Image.Image, Image.Image, Image.Image]:
    """Return augmentation cat plus matched square cat/dog MixUp sources."""
    # Bias right to keep the walking cat and the asymmetric chair/planter cues.
    aug_cat = square_crop(load_rgb(AUGMENTATION_CAT), horizontal_bias=0.65)

    pair = load_rgb(MIXUP_PAIR)
    midpoint = pair.width // 2
    divider_half = max(2, pair.width // 320)
    cat_panel = pair.crop((0, 0, midpoint - divider_half, pair.height))
    dog_panel = pair.crop((midpoint + divider_half, 0, pair.width, pair.height))
    # The generated diptych is portrait within each half.  Bias upward to keep
    # faces and shoulders visible in the square MixUp/CutMix teaching panels.
    mix_cat = square_crop(cat_panel, vertical_bias=0.14)
    mix_dog = square_crop(dog_panel, vertical_bias=0.14)
    return aug_cat, mix_cat, mix_dog


def reflect_shift(image: Image.Image, *, dx: int, dy: int) -> Image.Image:
    """Translate an image while filling exposed pixels by reflection."""
    array = np.asarray(image)
    height, width = array.shape[:2]
    pad = max(abs(dx), abs(dy)) + 4
    padded = np.pad(array, ((pad, pad), (pad, pad), (0, 0)), mode="reflect")
    left = pad - dx
    top = pad - dy
    return Image.fromarray(padded[top : top + height, left : left + width])


def add_sensor_noise(
    image: Image.Image,
    *,
    rng: np.random.Generator,
    sigma: float,
) -> Image.Image:
    array = np.asarray(image, dtype=float)
    noisy = np.clip(array + rng.normal(0, sigma, array.shape), 0, 255).astype(np.uint8)
    return Image.fromarray(noisy)


def f_augmentation_gallery(source: Image.Image) -> None:
    base = source.resize((960, 960), Image.Resampling.LANCZOS)

    # These are the exact TorchVision v2 calls printed on the slides.  Fixed
    # seeds select one reproducible draw from each stochastic transform.
    transforms = (
        v2.Identity(),
        v2.RandomResizedCrop(512, scale=(0.45, 0.45)),
        v2.RandomHorizontalFlip(p=0.5),
        v2.ColorJitter(brightness=0.4, saturation=0.6, hue=0.2),
        v2.GaussianBlur(21, sigma=4.0),
        v2.RandomRotation(20, fill=(247, 245, 240)),
    )
    seeds = (0, 4, 0, 28, 0, 11)
    outputs = []
    for transform, seed in zip(transforms, seeds):
        torch.manual_seed(seed)
        outputs.append(transform(base))

    views = [
        ("original", outputs[0]),
        ("random resized crop", outputs[1]),
        ("horizontal flip", outputs[2]),
        ("colour jitter", outputs[3]),
        ("Gaussian blur", outputs[4]),
        ("random rotation", outputs[5]),
    ]

    filenames = (
        "augmentation_original_v2_hd.png",
        "augmentation_crop_v2_hd.png",
        "augmentation_flip_v2_hd.png",
        "augmentation_colour_v2_hd.png",
        "augmentation_blur_v2_hd.png",
        "augmentation_rotate_v2_hd.png",
    )
    for filename, (_, view) in zip(filenames, views):
        view.save(OUT / filename)

    fig, axes = plt.subplots(2, 3, figsize=(8.8, 5.9))
    for ax, (label, view) in zip(axes.flat, views):
        ax.imshow(view, interpolation="lanczos")
        ax.set_title(
            label, fontsize=12.5, color=TEAL if label == "original" else INK, pad=7
        )
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(1.4 if label == "original" else 0.8)
            spine.set_color(TEAL if label == "original" else MUTED)
    fig.tight_layout(pad=0.12, w_pad=0.7, h_pad=1.0)
    save(fig, "augmentation_gallery_hd", raster_only=True, dpi=260)


def random_training_view(
    base: Image.Image,
    *,
    rng: np.random.Generator,
) -> Image.Image:
    dx = int(rng.integers(-58, 59))
    dy = int(rng.integers(-46, 47))
    view = reflect_shift(base, dx=dx, dy=dy)
    if rng.random() < 0.5:
        view = ImageOps.mirror(view)
    view = ImageEnhance.Brightness(view).enhance(float(rng.uniform(0.90, 1.10)))
    view = ImageEnhance.Contrast(view).enhance(float(rng.uniform(0.88, 1.15)))
    view = ImageEnhance.Color(view).enhance(float(rng.uniform(0.78, 1.18)))
    return view


def f_augmentation_batch(source: Image.Image) -> None:
    """Eight deterministic draws that mimic a pre-flight batch inspection."""
    base = source.resize((900, 900), Image.Resampling.LANCZOS)
    rng = np.random.default_rng(2026)
    views = [random_training_view(base, rng=rng) for _ in range(8)]

    fig, axes = plt.subplots(2, 4, figsize=(8.6, 4.15))
    for ax, view in zip(axes.flat, views):
        ax.imshow(view, interpolation="lanczos")
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)
            spine.set_color(MUTED)
    fig.subplots_adjust(
        left=0.005,
        right=0.995,
        bottom=0.01,
        top=0.99,
        wspace=0.055,
        hspace=0.055,
    )
    save(fig, "augmentation_batch_audit_hd", raster_only=True, dpi=260)


def f_mixup_cutmix(cat_source: Image.Image, dog_source: Image.Image) -> None:
    lam = 0.70
    side = 900
    cat = np.asarray(cat_source.resize((side, side), Image.Resampling.LANCZOS))
    dog = np.asarray(dog_source.resize((side, side), Image.Resampling.LANCZOS))
    mix = np.clip(
        lam * cat.astype(float) + (1 - lam) * dog.astype(float), 0, 255
    ).astype(np.uint8)

    cut = cat.copy()
    # A 450x450 patch occupies exactly 25% of the 900x900 canvas.
    patch = side // 2
    top = 0
    left = (side - patch) // 2
    cut[top : top + patch, left : left + patch] = dog[
        top : top + patch,
        left : left + patch,
    ]

    panels = [
        (cat, "cat", TEAL),
        (dog, "dog", ACC),
        (mix, "MixUp\n0.70 cat + 0.30 dog", BLUE),
        (cut, "CutMix\n0.75 cat + 0.25 dog", GREEN),
    ]
    fig, axes = plt.subplots(1, 4, figsize=(10.6, 3.15))
    for ax, (arr, label, colour) in zip(axes, panels):
        ax.imshow(arr, interpolation="lanczos")
        ax.set_title(label, color=colour, fontsize=12, weight=600, pad=7)
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(1.2)
            spine.set_color(colour)
    fig.suptitle(
        "mix the supervision whenever you mix the image",
        fontsize=15,
        weight=600,
        y=1.03,
    )
    fig.tight_layout(w_pad=1.1)
    save(fig, "mixup_cutmix_hd", raster_only=True, dpi=260)

    # Also save the exact pixel operands separately.  The lecture uses these
    # as larger, text-free panels so labels remain native Typst text.
    Image.fromarray(cat).save(OUT / "mixup_cat_hd.png")
    Image.fromarray(mix).save(OUT / "mixup_70_hd.png")
    Image.fromarray(dog).save(OUT / "mixup_dog_hd.png")
    Image.fromarray(cut).save(OUT / "cutmix_25_hd.png")


def f_randaugment_examples(source: Image.Image) -> None:
    """High-resolution examples composed from operations in the RA pool.

    These are visual explanations of sequential policy composition, not a
    claim that every panel came from one particular TorchVision magnitude
    index.  The slide keeps that distinction explicit.
    """
    base = source.resize((900, 900), Image.Resampling.LANCZOS)
    fill = (247, 245, 240)

    rotate_color = base.rotate(
        18,
        resample=Image.Resampling.BILINEAR,
        expand=False,
        fillcolor=fill,
    )
    rotate_color = ImageEnhance.Color(rotate_color).enhance(1.42)

    solarize_translate = ImageOps.solarize(base, threshold=154)
    solarize_translate = solarize_translate.transform(
        base.size,
        Image.Transform.AFFINE,
        (1, 0, -72, 0, 1, 0),
        resample=Image.Resampling.BILINEAR,
        fillcolor=fill,
    )

    posterize_contrast = ImageOps.posterize(base, bits=5)
    posterize_contrast = ImageEnhance.Contrast(posterize_contrast).enhance(1.38)

    for filename, image in (
        ("randaugment_original_hd.png", base),
        ("randaugment_rotate_color_hd.png", rotate_color),
        ("randaugment_solarize_translate_hd.png", solarize_translate),
        ("randaugment_posterize_contrast_hd.png", posterize_contrast),
    ):
        image.save(OUT / filename)


def f_mc_dropout_bridge() -> None:
    """Schematic stochastic functions: agreement near data, disagreement away."""
    rng = np.random.default_rng(7)
    x = np.linspace(-3.25, 3.25, 420)
    train_x = np.linspace(-1.75, 1.75, 11)
    train_y = np.sin(1.35 * train_x)
    base = np.sin(1.35 * x)
    outside = np.maximum(np.abs(x) - 1.65, 0.0)

    samples = []
    for _ in range(18):
        a, b, c = rng.normal(0, [0.12, 0.06, 0.025])
        smooth_noise = a + b * x + c * (x**2 - 2.0)
        samples.append(base + (0.045 + 0.62 * outside**1.35) * smooth_noise)
    samples = np.asarray(samples)

    fig, ax = plt.subplots(figsize=(8.8, 3.6))
    ax.axvspan(-3.25, -1.75, color=ACC, alpha=0.08, lw=0)
    ax.axvspan(1.75, 3.25, color=ACC, alpha=0.08, lw=0)
    for curve in samples:
        ax.plot(x, curve, color=BLUE, alpha=0.22, lw=1.2)
    ax.plot(
        x, samples.mean(axis=0), color=INK, lw=2.6, label="mean of T stochastic passes"
    )
    ax.scatter(
        train_x, train_y, s=32, color=TEAL, edgecolor="white", linewidth=0.5, zorder=5
    )
    ax.axvline(-1.75, color=MUTED, lw=1.0, ls="--")
    ax.axvline(1.75, color=MUTED, lw=1.0, ls="--")
    ax.text(
        0,
        -1.38,
        "training support → masks mostly agree",
        ha="center",
        color=TEAL,
        fontsize=11,
    )
    ax.text(
        2.52,
        1.20,
        "away from data\npasses disagree",
        ha="center",
        color=ACC,
        fontsize=11,
    )
    ax.set_xlabel("input x")
    ax.set_ylabel("prediction")
    ax.set_xticks([-3, -1.75, 0, 1.75, 3])
    ax.set_xticklabels(["−3", "edge", "0", "edge", "3"])
    ax.set_yticks([])
    ax.set_ylim(-1.55, 1.55)
    ax.legend(frameon=False, loc="upper left", fontsize=10.5)
    ax.set_title(
        "MC dropout bridge · keep masks stochastic and measure disagreement",
        fontsize=13,
    )
    fig.text(
        0.995,
        0.01,
        "schematic — uncertainty must be validated, not assumed",
        ha="right",
        color=MUTED,
        fontsize=9.5,
    )
    save(fig, "mc_dropout_bridge")


def main() -> None:
    augmentation_cat, mix_cat, mix_dog = load_teaching_photos()
    f_augmentation_gallery(augmentation_cat)
    f_augmentation_batch(augmentation_cat)
    f_mixup_cutmix(mix_cat, mix_dog)
    f_randaugment_examples(augmentation_cat)
    f_mc_dropout_bridge()
    print(f"wrote practical Lecture 7 figures to {OUT}")


if __name__ == "__main__":
    main()
