const assert=require('node:assert/strict');
const fs=require('node:fs');
const M=require('../interactives/cnn/model.js');
const close=(a,b,tol=1e-7)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
assert.deepEqual(M.conv(M.base,M.kernels.horizontal),[[-3,-3,-3],[-3,-3,-3],[3,3,3]]);
assert.deepEqual(M.conv(M.base,M.kernels.horizontal,{p:1,s:2}),[[0,0,0],[-2,-3,-2],[2,3,2]]);
assert.deepEqual(M.conv(M.base,M.kernels.horizontal,{d:2}),[[0]]);
assert.equal(M.size(6,3,1,2),3);
assert.equal(M.size(32,3,2,1,2),32);
assert.deepEqual(M.gradient1d([1,2,3,4],[1,-1]),{y:[-1,-1,-1],dw:[-6,-9],dx:[-1,0,0,1],loss:1.5});
assert.deepEqual(M.gradient1d([2,1,3],[.5,-1],[1,2]),{y:[0,-2.5],dw:[4,7],dx:[.5,0,-2],db:3});
assert.deepEqual(M.conv(M.mlEdge,M.kernels.vertical),Array.from({length:4},()=>[0,3,3,0]));
assert.equal(M.lenet(32).flat,400);assert.equal(M.lenet(32).total,61706);
assert.equal(M.lenet(28).flat,256);assert.equal(M.lenet(28).total,44426);
assert.deepEqual(M.receptive([{k:3},{k:2,s:2},{k:3}]).map(({r,j})=>[r,j]),[[3,1],[4,2],[8,2]]);
assert.deepEqual(M.pool([[0,1,2,0]],'max',1,1),[[0,1,2,0]]);
assert.deepEqual(M.pool([[1,2],[3,4]]),[[4]]);
assert.deepEqual(M.pool([[1,2],[3,4]],'mean'),[[2.5]]);
assert.equal(M.receptive([{k:3},{k:3}]).at(-1).r,5);
assert.deepEqual(M.receptive([{k:3,s:2},{k:3}]).at(-1),{r:7,j:2,start:3.5});
assert.equal(M.receptive([{k:3,d:2},{k:3,d:2}]).at(-1).r,9);
const first=M.ledger(32,3,16),second=M.ledger(16,16,32);
assert.equal(first.params,448);assert.equal(first.macs,442368);
assert.equal(second.params,4640);assert.equal(second.macs,1179648);
assert.equal(first.params+second.params+330,5418);
assert.equal(first.macs+second.macs+320,1622336);
assert.equal(M.ledger(64,3,16).macs,4*first.macs);
assert.equal(M.ledger(64,3,16).params,first.params);
assert.throws(()=>M.ledger(32,3,16,3,1,1,1,2));
const x=M.grid(6,6,(r,c)=>(r===2&&c===0)||(r===4&&c===3)?1:0),k=[[0,0,0],[1,2,1],[0,0,0]];
const testShift=(s,dx,circular)=>{
  const a=M.conv(M.shift(x,dx,0,circular),k,{p:1,s,circular});
  const b=M.shift(M.conv(x,k,{p:1,s,circular}),Math.floor(dx/s),0,circular);
  return Math.max(...a.flatMap((row,r)=>row.map((v,c)=>Math.abs(v-b[r][c]))));
};
assert.equal(testShift(1,1,true),0);
assert.ok(testShift(2,1,true)>0);
assert.equal(testShift(2,2,true),0);
assert.ok(testShift(1,1,false)>0);
const initial=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../interactives/cnn/initial-model.json')));
assert.deepEqual(initial,{model:M.init(),samples:M.samples});
// Central finite differences are independent of the handwritten backpropagation.
const m=M.init(),g=M.objective(m).grad,eps=1e-6;
let count=0,maxError=0;
function walk(a,b){Object.keys(a).forEach(key=>{if(typeof a[key]==='object')walk(a[key],b[key]);else{const v=a[key];a[key]=v+eps;const plus=M.objective(m,M.samples,false).loss;a[key]=v-eps;const minus=M.objective(m,M.samples,false).loss;a[key]=v;const num=(plus-minus)/(2*eps);maxError=Math.max(maxError,Math.abs(num-b[key]));close(num,b[key],2e-7);count++;}});}
walk(m,g);assert.equal(count,26);
const before=M.objective(m).loss;
for(let i=0;i<600;i++)M.step(m);
const after=M.objective(m);assert.ok(after.loss<before/100);assert.equal(after.accuracy,1);
console.log(JSON.stringify({passed:true,gradientParameters:count,maxGradientError:maxError,initialLoss:before,lossAfter600:after.loss,trainingCorrect:6},null,2));
