import { unit, dot, difference } from './math.js';
export const chapters = [
 {id:'first-match',label:'One image, many captions',title:'How does a picture find its words?',question:'Choose the caption you expect to win. What does the model compare?',a:'chelsea',candidates:['caption-chelsea','caption-retriever-photo','caption-coffee','caption-rocket'],kind:'single',jump:'captions',changed:'One image is compared with four text candidates.',fixed:'One model, one image vector, the same caption menu.',notice:'The model returns 768 numbers. We supply the captions and rank their dot products. It has not written a caption.',limit:'The highest score only identifies the best option in this menu.'},
 {id:'hear-a-match',label:'Listen before looking',title:'Can a bark find a picture?',question:'Play the recording first. Predict which image will be closest.',a:'sound-dog',candidates:['newfoundland','Persian','photo-beach','photo-fire','photo-rooster','photo-train'],kind:'single',jump:'listen',changed:'The query is a waveform; the candidates are photographs.',fixed:'The image index is reused. There is no speech transcript.',notice:'Audio and image inputs produce vectors of the same length. The dot product works across these modalities.',limit:'A shared space does not guarantee every cross-modal match. Try the caption menu below.',alternate:['caption-sound-dog','caption-sound-crying_baby','caption-sound-sneezing','caption-sound-rooster','caption-sound-rain','caption-sound-sea_waves']},
 {id:'watch-a-match',label:'Video becomes searchable',title:'What does the model see in a video?',question:'Play the excerpt. Which description should retrieve it?',a:'film-coffee',candidates:['caption-commons-coffee','caption-commons-puppy','caption-commons-waves','caption-commons-geese'],kind:'single',jump:'moments',changed:'A clip is represented using sampled frames.',fixed:'This lab samples one frame each second, without the soundtrack.',notice:'Store one vector per short time window to retrieve a moment. An embedding is not a frame-by-frame description.',limit:'A brief event between sampled frames can be missed. Sound in the original video cannot affect this lab’s video vector.'},
 {id:'change-colour',label:'Change the colour',title:'Same kind of object. Different colour.',question:'Will the red and blue descriptions exchange places?',a:'red-mug',b:'blue-mug',candidates:['caption-red-mug','caption-blue-mug','caption-coffee','caption-commons-pizza'],kind:'compare',jump:'neighbors',changed:'We replace the red-mug image with the blue-mug image.',fixed:'The model, dimensions and candidate captions stay fixed.',notice:'Read each row across: the same candidate has a score before and after. The image vector changes; the text vectors do not.',limit:'These are generated teaching images, not a pixel-perfect controlled edit. Other visual details can differ.'},
 {id:'change-style',label:'Change the style',title:'Does a sketch still look like a dog?',question:'Can the model preserve the subject and notice the drawing style?',a:'retriever-photo',b:'retriever-sketch',candidates:['caption-retriever-photo','caption-retriever-sketch','caption-Persian','caption-commons-puppy'],kind:'compare',jump:'neighbors',changed:'A photograph-style dog becomes a pencil sketch.',fixed:'The caption menu and model remain fixed.',notice:'Both subject and style can contribute to similarity. Inspect the scores instead of assuming the representation ignores style.',limit:'Generated image pairs illustrate sensitivity; they do not isolate one causal variable.'},
 {id:'hat-direction',label:'Subtract two images',title:'Which words align with the change?',question:'What should happen to every score if we reverse before and after?',a:'portrait',b:'portrait-hat',candidates:['caption-portrait-hat','caption-portrait','caption-astronaut','caption-coffee'],kind:'delta',jump:'delta',changed:'Compare a normalized difference instead of either original image.',fixed:'The same pair and text candidates. Reversing the pair negates the direction.',notice:'Δ = (v_after − v_before) / ‖v_after − v_before‖. A text vector aligned with this direction has a positive dot product.',limit:'This is an exploratory association, not a causal explanation of an image edit. A direction score is not an ordinary image–text score.'},
 {id:'missing-answer',label:'Remove the right answer',title:'A winner can still be wrong.',question:'If the cat caption disappears, will the search know that it is missing?',a:'chelsea',candidates:['caption-chelsea','caption-retriever-photo','caption-coffee','caption-rocket'],kind:'missing',jump:'classify',changed:'Remove the best caption from the candidate menu.',fixed:'Every embedding and every remaining cosine stays exactly the same.',notice:'Argmax always returns a candidate if the menu is non-empty. It is a ranking rule, not a learned “none of these” decision.',limit:'A cosine is not confidence. Reliable rejection needs a separately evaluated decision rule.'},
 {id:'different-words',label:'Change the language',title:'Can different languages point to the same image?',question:'Which of these sentences might match the cat most strongly?',a:'chelsea',candidates:['phrase-cat-en','phrase-cat-hi','phrase-cat-fr','phrase-cat-es'],kind:'single',jump:'languages',changed:'Equivalent teaching descriptions in four languages.',fixed:'The cat image and its embedding stay fixed.',notice:'The sentences have different token sequences and vectors, yet can align with the same image. Equal meaning need not produce equal scores.',limit:'These saved sentences use document formatting. The live text-search experiment uses a query prefix; it is a different input and may rank differently.'},
 {id:'shorter-vectors',label:'Keep fewer numbers',title:'What do we give up to make the index smaller?',question:'Predict whether the winner will change at 128 dimensions.',a:'sound-dog',candidates:['caption-sound-dog','caption-sound-crying_baby','caption-sound-sneezing','caption-sound-rooster','caption-sound-rain','caption-sound-sea_waves'],kind:'dimensions',jump:'explorer',changed:'Keep the first 128 coordinates, then normalize both vectors again.',fixed:'Same model outputs and candidate menu. No model is retrained.',notice:'Here the 128d vector ranks the dog description first, while 768d ranks crying baby first. More dimensions do not win every individual example. Float32 storage falls from 3,072 to 512 bytes.',limit:'This reduces index memory, not the model download. One menu cannot establish overall retrieval quality.'},
 {id:'take-it-further',label:'Build something with it',title:'The representation is the starting point.',question:'Which parts of an application use the embedding, and which parts still need to be built?',kind:'summary'}
];
export function chapterScores(chapter, vectors, {alternate=false,removed=false,reversed=false}={}) {
 const ids=alternate&&chapter.alternate?chapter.alternate:chapter.candidates;
 if(!ids)return [];
 let first=unit(vectors[chapter.a].vector), second=chapter.b?unit(vectors[chapter.b].vector):null;
 if(chapter.kind==='delta') {
  first=difference(second,first); if(reversed)first=first.map(x=>-x); second=null;
 }
 return ids.filter(id=>!(removed&&id===chapter.candidates[0])).map(id=>{
  const candidate=unit(vectors[id].vector);
  return {id,a:dot(first,candidate),b:chapter.kind==='dimensions'?dot(unit(first,128),unit(candidate,128)):second?dot(second,candidate):null};
 }).sort((x,y)=>y.a-x.a);
}
